app/models.py
from . import db
from flask_login import UserMixin,current_user
from werkzeug.security import generate_password_hash,check_password_hash
from datetime import datetime

from . import login_manager
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# Ngo class
class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255),unique = True,nullable = False)
    email  = db.Column(db.String(255),unique = True,nullable = False)
    secure_password = db.Column(db.String(255),nullable = False)


    event = db.relationship('Event', backref='user', lazy='dynamic')


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.secure_password = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.secure_password,password)


    def __repr__(self):
        return f'User {self.username}'

class Event(db.Model):
    __tablename__ = 'events'
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(255),nullable = False)
    event_pic_path = db.Column(db.String())
    description = db.Column(db.Text(), nullable = False)
    category = db.Column(db.String(255), index = True,nullable = False)
    value = db.Column(db.Integer, nullable = False) 
    time = db.Column(db.DateTime, default = datetime.utcnow)


    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    donor = db.relationship('Donor',backref='event',lazy='dynamic')
   
    @classmethod
    def clear_event(cls):
        Bloc.event.clear()
    
    @classmethod
    def get_events(cls):
        event = Event.query.filter_by(id = id).all()
        return event

    def delete(self, id):
        donors = Donor.query.filter_by(id = id).all()
        for donor in donors:
            db.session.delete(donor)
            db.session.commit()
        db.session.delete(self)
        db.session.commit()    
    
    def __repr__(self):
        return f'Event {self.name}'

        

class Donor(db.Model):
    __tablename__ = 'donors'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255),nullable = False)
    email  = db.Column(db.String(255),nullable = False)
    amount = db.Column(db.Integer, nullable = False)

    event_id = db.Column(db.Integer,db.ForeignKey('events.id'))


    @classmethod
    def clear_comment(self):
        Donor.donors.clear()

    @classmethod
    def get_donors(cls, id):
        donors = Donor.query.filter_by(event_id = id).all()
        return donors   

     
    def __repr__(self):
        return f'Donor {self.name}'

app/main/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SelectField, TextAreaField, SubmitField,IntegerField
from wtforms.validators import Required,Email


class EventForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    category = SelectField('Category', choices=[('Food','Food'),('Clothes','Clothes'),('Money','Money'),('Books','Books')],validators=[Required()])
    description = TextAreaField('Your event description', validators=[Required()])
    value = IntegerField('Amount need for event', validators=[Required()])
    event_pic_path = StringField('Upload image url')
    submit = SubmitField('Save')


class DonorForm(FlaskForm):
    name = StringField('Your name', validators=[Required()])
    email = StringField('Your Email Address',validators=[Required(),Email()])
    value = IntegerField('Amount donated', validators=[Required()])
    submit = SubmitField('Donate')    

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import IMAGES, UploadSet,configure_uploads
from flask_mail import Mail





login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


bootstrap = Bootstrap()
db = SQLAlchemy()

photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)



    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    #Initializing Flask Extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    db.init_app(app)
    

    # Will add the views and forms

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # setting config
    from .requests import configure_request
    configure_request(app)
    # configure UploadSet
    configure_uploads(app,photos)
    
    mail.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,current_app
from ..models import User,Event,Donor
from . import main
from flask_login import login_required
from .. import db,photos
from .forms import EventForm,DonorForm
from flask_login import current_user

# Views
@main.route('/')
def index():
    event = Event.query.order_by(Event.time.desc()).all()
    food = Event.query.filter_by(category = 'Food').order_by(Event.time.desc()).all() 
    clothes = Event.query.filter_by(category = 'Clothes').order_by(Event.time.desc()).all()
    money = Event.query.filter_by(category = 'Money').order_by(Event.time.desc()).all()
    books = Event.query.filter_by(category = 'Books').order_by(Event.time.desc()).all()
    title ='Charity'
    return render_template('index.html', food = food, clothes = clothes, money = money, books= books, title=title, event=event)

@main.route('/new_event', methods = ['POST','GET'])
@login_required
def add_event():
    form = EventForm()
    if form.validate_on_submit():
        title = form.title.data
        description = form.description.data
        category = form.category.data
        value = form.value.data
        user_id = current_user
        if form.event_pic_path.data:
            event_pic_path = form.event_pic_path.data     
            if form.validate_on_submit():

                new_event = Event(description=description,user_id=current_user._get_current_object().id,event_pic_path=event_pic_path,category=category,value=value,title=title)
                db.session.add(new_event)
                db.session.commit()
        
            return redirect(url_for('main.index'))
        else:
            event_pic_path = 'https://www.freevector.com/uploads/vector/preview/25765/Charity_-01.jpg'    
            if form.validate_on_submit():

                new_event = Event(description=description,user_id=current_user._get_current_object().id,event_pic_path=event_pic_path,category=category,title=title,value=value)
                db.session.add(new_event)
                db.session.commit()
        
            return redirect(url_for('main.index'))

        
    return render_template('event.html', form = form)



@main.route('/donor/<int:event_id>', methods = ['POST','GET'])
def donor(event_id):
    form = DonorForm()
    event = Event.query.get(event_id)
    all_donors = Donor.query.filter_by(event_id = event_id).all()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        amount = form.value.data
        event_id = event_id
        new_donor = Donor(name = name, email = email, amount = amount,event_id = event_id)
        
        db.session.add(new_donor)
        db.session.commit()
        return redirect(url_for('.index', event_id = event_id))
    return render_template('donation.html', form =form, event = event,all_donors=all_donors) 

@main.route('/index/<int:id>/delete',methods = ['GET','POST'])
@login_required
def delete(id):
    current_event = Event.query.filter_by(id = id).first()
    if current_event.user != current_user:
        abort(404)
    db.session.delete(current_event)
    db.session.commit()

    return redirect(url_for('.index'))    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    {% block head%} {% endblock %}
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Blog</title>
    {% endif %}

    <link rel="icon" href="https://previews.123rf.com/images/nickshot/nickshot1504/nickshot150400039/39524514-woman-hands-holding-heart-isolated-on-green-background-family-health-charity-and-medicine-concept-.jpg">

</head>

<body>


    {% block navbar %} {% include 'navbar.html' %} {% endblock %} {% block content%} {%endblock%} {% block footer %} {% include 'footer.html' %} {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>


</body>

</html>

app/templates/donation.html
{% extends 'base.html'%} {% import 'bootstrap/wtf.html' as wtf%} {% block content %}
<section class="donors">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="donors_input">
                    <h2>DONATION NOW</h2>

                    <h5>
                        {{wtf.quick_form(form)}}

                    </h5>

                </div>
                <div class="donors_image">
                    
                    <div class="donors_featured owl-carousel owl-theme">
                        <div class="item">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock%}

app/templates/event.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

<div class="container-fluid"
    style="background-image:url('https://previews.123rf.com/images/nickshot/nickshot1504/nickshot150400039/39524514-woman-hands-holding-heart-isolated-on-green-background-family-health-charity-and-medicine-concept-.jpg'); background-size: cover; height: 100.4vh; background-position: center;margin-top: -0.55cm;">
    <div class="row">
        <div class="col-md-2"> </div>
        <div class="col-md-8">
            <h3
                style="font-weight: bold;font-size: 50px;margin-top: 80px;letter-spacing:2px;font-family: 'Times New Roman', Times, serif; color: black;text-align: center;">
                Create An Event</h3>
            <br>
            <div style="color: white; background-color: transparent;">
                {{wtf.quick_form(form)}}
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/footer.html
<!-- <footer class=" text-center text-lg-start" style="background-color: rgb(17, 160, 41);">
    <div class="container-fluid p-4">
      <div class="row">
        <div class="col-lg-12 col-md-12 mb-4 mb-md-0">
          <h3 class="text-uppercase text-dark font-weight-bold" >About US</h3>
          <p style="color: #ffffff;">
            We are available and ready to help. Easiest way to help! Donate to others now.
            Give love. Give to others! Services: Donating to others, Helping those in Need, Helping the community.
          </p>
        </div>
      </div>
    </div>
    <div class="text-center p-3 " style="color: #ffffff;" style="background-color: rgb(8, 56, 36)">
      © 2020 Copyright:
      <a class="text-white" href="" style="color: #ffffff;">CHARITY ONLINE</a>
    </div>
  </footer> -->

  <section id="footer" style="background: #086d0d !important;">
		<div class="container" style="background: #086d0d !important;">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
					<ul class="list-unstyled list-inline social text-center">
						<li class="list-inline-item"><a href=""><i class="fa fa-facebook"></i></a></li>
						<li class="list-inline-item"><a href=""><i class="fa fa-twitter"></i></a></li>
						<li class="list-inline-item"><a href=""><i class="fa fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href=""><i class="fa fa-google-plus"></i></a></li>
						<li class="list-inline-item"><a href="" target="_blank"><i class="fa fa-envelope"></i></a></li>
					</ul>
				</div>
				<hr>
			</div>	
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
					<p class="h6" style="color: #ffffff;">© All right Reversed.<a class="text-green ml-2" href="" target="_blank">Charity Online</a></p>
				</div>
				<hr>
			</div>	
		</div>
	</section>
	

app/templates/fourOwfour.html
{% block content %}
<div class="text-center">
    <i class="fas fa-exclamation-triangle"></i>
</div>
<h1 class="text-center">WHOOOPS we can't find that page<br>Or you are trying to view a page with no access. </h1>

{% endblock %}

app/templates/index.html
{% import 'macros.html' as macro%}
{% extends 'base.html'%}
{% block head%}
<!-- <link rel="stylesheet" href="../static/style.css"> -->
{% endblock %}
{% block content%}

<div class="jumbotron"
    style="background-image:url('https://res.cloudinary.com/mugisha-thierry/image/upload/v1608196334/charity2_wrbfhr.jpg');background-size: cover; background-position: center;">
    <div>
        <h1 class="text-center"
            style="letter-spacing: 5px;font-family: 'Euphoria Script', cursive;color:#2a8000;height: 10px;padding-top: 100px;">
            <strong>
                Charity Online</strong></h1>
        <p class="text-center"
            style="color: black;font-style: italic;font-family: 'Times New Roman', Times, serif; padding-top: 100px; padding-bottom: 150px;">
            "We make a living by what we get, but we make a life by what we give"<br>Winston churchill</p>
    </div>

</div>

<div class="container" id="particles-js">
    <style>
        i{color: green;font-size: 40px;}
    </style>
    <ul class="nav nav-pills nav-justified nav-fill" role="tablist" style="padding-bottom: 20px;">
        <br><br><br>
        <li class="nav-item">
            <a id="cats" class="nav-link" data-toggle="tab" style="background-color:green;" href="#religion"
                style="color: black"><strong>All event</strong></a><br>
        </li>
        <li class="nav-item">
            <a id="cats" class="nav-link" data-toggle="tab" style="background-color:#e3f2fd;" href="#education"
                style="color: black"><strong>Food</strong></a><br>
        </li>
        <li class="nav-item">
            <a id="cats" class="nav-link" data-toggle="tab" style="background-color:#e3f2fd;" href="#music"
                style="color: black"><strong>Clothes</strong></a><br>
        </li>
        <li class="nav-item">
            <a id="cats" class="nav-link" data-toggle="tab" style="background-color:#e3f2fd;" href="#education"
                style="color: black"><strong>Money</strong></a><br>
        </li>
        <li class="nav-item">
            <a id="cats" class="nav-link" data-toggle="tab" style="background-color:#e3f2fd;" href="#education"
                style="color: black"><strong>Books</strong></a><br>
        </li>
    </ul>
    <hr>
    <div class="tab-content">

        <div class="container tab-pane active" id="religion" style="background-color:#d6dfe6;"><br>

            {{macro.display(event)}}
        </div>

        <div class="container tab-pane fade" id="education" style="background-color:#cdd6dd;"><br>

            {{macro.display(food)}}

        </div>
        <div class="container tab-pane fade" id="music" style="background-color: #cdd6dd;"><br>

            {{macro.display(clothes)}}

        </div>
        <div class="container tab-pane fade" id="music" style="background-color: #cdd6dd;"><br>

            {{macro.display(money)}}

        </div>
        <div class="container tab-pane fade" id="music" style="background-color: #cdd6dd;"><br>

            {{macro.display(books)}}

        </div>
        
        <hr>

    </div>
</div>

<div id="contact">
    <div class="container">
        <br><br>
        <h1 class="text-center" style="color: green;"><strong> Contact Details</h1></strong>
        <div class="row">
            <div class="col-sm-6" style="padding:3%">
                <form action="" style="padding:10%" id="form1">
                    <div class="form-group">
                        <input type="text" class="form-control" name="name" id="name" placeholder="Name" required="">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="email" id="email" placeholder="E-mail"
                            required="">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="phone" id="phone" placeholder="Phone Number"
                            required="">
                    </div>
                    <div class="form-group">
                        <textarea type="text" class="form-control" name="message_body" id="message_body"
                            placeholder="Your Message" required="" style="height:100px; "></textarea>
                    </div>
                    <button class="btn" type="submit" style="width: 100%; background-color: #2a8000; color: aliceblue;"
                        data-toggle="modal" data-target="#messageReceived">Submit form</button>
                </form>
            </div>
            <div class="col-sm-6" style="padding:4%">
                <div class="card" style="background-color: #dfede3;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <i class='fas fa-map-marker-alt'></i>
                            </div>
                            <div class="col-sm-8">
                                <h3 class="card-title">Our Location</h3>
                                <p class="card-text">Kigali,Rwanda
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="card" style="background-color: #dfede3;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <i class='fas fa-phone'></i>
                            </div>
                            <div class="col-sm-8">
                                <h3 class="card-title">Phone</h3>
                                <p class="card-text">Mobile:+250 788 333 888
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="card" style="background-color: #dfede3;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <i class='fas fa-envelope-open-text'></i>
                            </div>
                            <div class="col-sm-8">
                                <h3 class="card-title">Our Email</h3>
                                <p class="card-text">charity.online@gmail.com
                                </p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

app/templates/macros.html
{% macro display(event) %}

<div class="container-fluid">
    <div class="row">
        {% if event %}
        {% for category in event %}
        <div class="col-md-4">
            <div class="card" style="background-color: white;">
                <div class="card-body">
                    <h5 class="card-title" style="font-weight: bolder;">{{category.title}}</h5>
                    <img class="card-img-top" src="{{category.event_pic_path}}" alt="Card image cap">
                    <p class="card-text">{{category.description}}</p>
                    <p class="card-text text-muted">BY: {{category.user.username}}</p>
                    <div>
                        <span class="mr-2"><i class="fas fa-hand-holding-usd"></i> People who donated : {{category.donor.count()}}</span><br>
                        <a href="{{url_for('main.donor',event_id = category.id)}}"
                            class="btn btn-success">Donate</a>

                        <a href="{{url_for('main.delete',id = category.id)}}"
                            class="btn btn-outline-danger">Delete</a><br><br>

                    </div>

                </div>
            </div>
        </div>

        {% endfor %}
        {% else %}
        <p class="card-title">No Event so far</p>
        {% endif %}
    </div>
</div>
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg fixed-top" style=" background-color: rgba(5, 66, 5, 0.7);">
  <a class="navbar-brand" href="/">
    <img src="https://previews.123rf.com/images/nickshot/nickshot1504/nickshot150400039/39524514-woman-hands-holding-heart-isolated-on-green-background-family-health-charity-and-medicine-concept-.jpg" width="30" height="30" alt="">
  </a>
  <a class="navbar-brand" href="/" style="color: black;font-weight: bold;">Charity Online</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/" style="color: black;font-weight: bold;">Home <span class="sr-only">(current)</span></a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0"></form>



      {% if current_user.is_authenticated %}
      <a class="btn btn-dark " href="{{url_for('main.add_event')}}"></span>Create event</a>
      <a class="btn btn-dark" href="{{url_for('auth.logout')}}"></span> Logout</a>
      {% else %}
      <a class="btn btn-dark " href="{{url_for('auth.register')}}">Register</a><br>
      <a class="btn btn-dark " href="{{url_for('auth.login')}}"><span class="glyphicon glyphicon-log-in"></span> Login</a>
      {%endif%}

    </form>
  </div>
</nav>